# Configura a URL base do servidor Ollama.
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

# Define o ID do modelo que o Langchain4j irá invocar no Ollama.
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b

# Define um timeout para a chamada.
# Se o modelo demorar mais de 600s para responder, a chamada falhará.
quarkus.langchain4j.ollama.timeout=600s

# --- Configuração do Embedding Model ---
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

# --- Configuração do PgVector ---
# A dimensão do vetor DEVE corresponder à do seu EmbeddingModel. O modelo 'nomic-embed-text' usa vetores de 768 dimensões.
quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
quarkus.langchain4j.pgvector.drop-table-first=true

# --- Configuração de Logging do LangChain4j ---
# Loga a requisição completa enviada para o LLM (incluindo o manifesto de Tools)
quarkus.langchain4j.log-requests=true

# Loga a resposta completa recebida do LLM (incluindo a chamada de Tool)
quarkus.langchain4j.log-responses=true