quarkus.http.port=8081

# Metadados do Servidor
quarkus.mcp.server.server-info.name=Travel Booking Tools Service
quarkus.mcp.server.server-info.version=1.0.0

# Permite ver o JSON-RPC de cada transação
quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=2000

# Datasource PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=booking
quarkus.datasource.password=booking
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/bookingdb

# Hibernate ORM
quarkus.hibernate-orm.database.generation=validate

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.clean-at-start=true